osx_image: xcode8.1
language: objective-c
script:
  - xcodebuild -workspace FileExplorer/FileExplorer.xcworkspace -scheme FileExplorerTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0'
