osx_image: xcode8.2
language: objective-c
before_install:
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 7 (10.1" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
script:
  - xcodebuild -workspace test clean FileExplorer/FileExplorer.xcworkspace -scheme FileExplorerTestHostApp -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO
