osx_image: xcode8.1
language: objective-c
script:
  - xcodebuild -workspace FileExplorer/FileExplorer.xcworkspace -scheme FileExplorerTestHostApp -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' test clean
